services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /home/server-1-mat/jellyfin_media:/media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.0.21
    extra_hosts:
      - "host.docker.internal:host-gateway"
    group_add:
      - "992"
    devices:   
      - /dev/dri/renderD128:/dev/dri/renderD128
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=2137
    volumes:
      - /home/server-1-mat/jellyfin_media/downloads:/downloads
      - /home/server-1-mat/media_config/qbittorrent:/config
    ports:
      - "2137:2137"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/server-1-mat/media_config/radarr:/config
      - /home/server-1-mat/jellyfin_media/movies:/movies
      - /home/server-1-mat/jellyfin_media/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/server-1-mat/media_config/sonarr:/config
      - /home/server-1-mat/jellyfin_media/series:/tv
      - /home/server-1-mat/jellyfin_media/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/server-1-mat/media_config/jackett:/config
      - /home/server-1-mat/jellyfin_media/downloads:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped

  
