version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /home/server-1-mat/jellyfin_media:/media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.0.21
    extra_hosts:
      - "host.docker.internal:host-gateway"
    group_add:
      - "992"
    devices:   
      - /dev/dri/renderD128:/dev/dri/renderD128
